import { CardDefinition } from '../../../types/cards';

export const followers: CardDefinition[] = [
  {
    id: 'airag_maker',
    name: 'Airag Maker',
    type: 'follower',
    guild: 'earth',
    cost: 2,
    strength: 2,
    health: 2,
    standingRequirement: { earth: 1 },
    description: 'Enters: Gain 1 standing with any guild.',
    abilities: [
      {
        timing: 'enters',
        effects: [{ type: 'gain_standing', player: 'self', guild: 'choose', amount: 1 }],
        description: 'Gain 1 standing with any guild.',
      },
    ],
  },
  {
    id: 'amu_river_armorer',
    name: 'Amu River Armorer',
    type: 'follower',
    guild: 'earth',
    cost: 3,
    standingRequirement: { earth: 1 },
    strength: 2,
    health: 2,
    description: 'Enters: Migrate → Gain 3 Mythium. Put a +1/+1 counter on a follower.',
    abilities: [{
      timing: 'enters',
      effects: [{
        type: 'migrate',
        effects: [
          { type: 'gain_mythium', player: 'self', amount: 3 },
          { type: 'add_counter', target: { kind: 'choose', filter: { type: 'follower', zone: ['board'] }, count: 1 }, counter: 'plus_one_plus_one', amount: 1 },
        ],
      }],
      description: 'Migrate → Gain 3 Mythium. Put a +1/+1 counter on a follower.',
    }],
  },
  {
    id: 'astute_tactician',
    name: 'Astute Tactician',
    type: 'follower',
    guild: 'earth',
    cost: 5,
    standingRequirement: { earth: 2 },
    strength: 5,
    health: 3,
    abilities: [
      {
        timing: 'attacks',
        effects: [{ type: 'gain_mythium', player: 'self', amount: 2 }],
        description: 'Gain 2 Mythium.',
      },
    ],
    description: 'Attacks: Gain 2 Mythium.',
  },
  {
    id: 'alamut_emissary',
    name: 'Alamut Emissary',
    type: 'follower',
    guild: 'void',
    cost: 4,
    standingRequirement: { void: 2 },
    strength: 2,
    health: 4,
    keywords: ['bloodshed']
  },
  {
    id: 'alert_warden',
    name: 'Alert Warden',
    type: 'follower',
    guild: 'moon',
    cost: 3,
    standingRequirement: { moon: 1 },
    strength: 4,
    health: 3,
    conditionalKeywords: [{
      keyword: 'stationary',
      condition: { type: 'standing_less_than', guild: 'moon', amount: 4 },
    }],
    description: 'While you have less than 4 Moon standing, Alert Warden has stationary.',
  },
  {
    id: 'alamut_saboteur',
    name: 'Alamut Saboteur',
    type: 'follower',
    guild: 'void',
    cost: 3,
    standingRequirement: { void: 2 },
    strength: 1,
    health: 4,
    abilities: [
      {
        timing: 'breach',
        effects: [{ type: 'discard', player: 'opponent', count: 1 }],
        description: 'Defending player discards a card.',
      },
    ],
    description: 'Breach: Defending player discards a card.',
  },
  {
    id: 'baleful_viper',
    name: 'Baleful Viper',
    type: 'follower',
    guild: 'void',
    cost: 4,
    standingRequirement: { void: 1 },
    strength: 1,
    health: 3,
    keywords: ['lethal'],
    abilities: [{
      timing: 'breach',
      effects: [{ type: 'gain_standing', player: 'self', guild: 'void', amount: 1 }],
      description: 'Gain 1 Void standing.',
    }],
    description: 'Lethal. Breach: Gain 1 Void standing.',
  },
  {
    id: 'caravan_guard',
    name: 'Caravan Guard',
    type: 'follower',
    guild: 'neutral',
    cost: 2,
    strength: 2,
    health: 4,
    keywords: ['stationary'],
    description: 'Stationary (This cannot attack.)',
  },
  {
    id: 'champion_of_the_tumen',
    name: 'Champion of the Tumen',
    type: 'follower',
    guild: 'earth',
    cost: 4,
    standingRequirement: { earth: 1 },
    strength: 4,
    health: 2,
    keywords: ['overwhelm'],
    description: 'Overwhelm (When this defeats a blocker, gain 1 power.)',
  },
  {
    id: 'dogtamer',
    name: 'Dogtamer',
    type: 'follower',
    guild: 'earth',
    cost: 1,
    standingRequirement: { earth: 1 },
    strength: 1,
    health: 1,
    description: 'Enters: Migrate → Gain 3 Mythium. (Either gain 1 Earth standing, or spend 1 Earth standing to gain 3 Mythium.)',
    abilities: [{
      timing: 'enters',
      effects: [
        { type: 'migrate', effects: [{ type: 'gain_mythium', player: 'self', amount: 3 }] },
      ],
      description: 'Migrate → Gain 3 Mythium.',
    }],
  },
  {
    id: 'earth_apprentice',
    name: 'Earth Apprentice',
    type: 'follower',
    guild: 'neutral',
    cost: 3,
    strength: 2,
    health: 2,
    description: 'Enters: Gain 1 Earth Standing. Enters: If you control at least 2 other followers, draw 1 card.',
    abilities: [
      {
        timing: 'enters',
        effects: [{ type: 'gain_standing', player: 'self', guild: 'earth', amount: 1 }],
        description: 'Gain 1 Earth Standing.',
      },
      {
        timing: 'enters',
        effects: [{
          type: 'conditional',
          condition: {
            type: 'min_card_count',
            filter: { type: 'follower', zone: ['board'], owner: 'controller', excludeSelf: true },
            count: 2,
          },
          effects: [{ type: 'draw_cards', player: 'self', count: 1 }],
        }],
        description: 'If you control at least 2 other followers, draw 1 card.',
      },
    ],
  },
  {
    id: 'generous_dealer',
    name: 'Generous Dealer',
    type: 'follower',
    guild: 'stars',
    cost: 5,
    standingRequirement: { stars: 1 },
    strength: 2,
    health: 4,
    description: 'Event and location cards you play cost 1 less.',
    passiveEffects: [{ type: 'cost_reduction', cardTypes: ['event', 'location'], amount: 1 }],
  },
  {
    id: 'khutuluns_kheshig',
    name: "Khutulun's Kheshig",
    type: 'follower',
    guild: 'earth',
    cost: 2,
    standingRequirement: { earth: 1 },
    strength: 1,
    health: 1,
    keywords: ['overwhelm'],
    abilities: [{
      timing: 'attacks',
      effects: [
        { type: 'add_counter', target: { kind: 'self' }, counter: 'plus_one_plus_one', amount: 1 },
      ],
      description: 'Put a +1/+1 counter on Khutulun\'s Kheshig.',
    }],
  },
  {
    id: 'stars_apprentice',
    name: 'Stars Apprentice',
    type: 'follower',
    guild: 'neutral',
    cost: 3,
    strength: 2,
    health: 2,
    description: 'Enters: Gain 1 Stars Standing. Enters: If you control a location, draw 1 card.',
    abilities: [
      {
        timing: 'enters',
        effects: [{ type: 'gain_standing', player: 'self', guild: 'stars', amount: 1 }],
        description: 'Gain 1 Stars Standing.',
      },
      {
        timing: 'enters',
        effects: [{
          type: 'conditional',
          condition: {
            type: 'min_card_count',
            filter: { type: 'location', zone: ['board'], owner: 'controller' },
            count: 1,
          },
          effects: [{ type: 'draw_cards', player: 'self', count: 1 }],
        }],
        description: 'If you control a location, draw 1 card.',
      },
    ],
  },
  {
    id: 'yam_operator',
    name: 'Yam Operator',
    type: 'follower',
    guild: 'neutral',
    cost: 1,
    strength: 1,
    health: 1,
    description: 'Enters: Play an event card, paying 1 mythium less.',
    abilities: [{
      timing: 'enters',
      effects: [{ type: 'play_card', target: { kind: 'choose', filter: { type: 'event', zone: ['hand'], owner: 'controller', canPay: { costReduction: 1 } }, count: 1 }, costReduction: 1 }],
      description: 'Play an event card, paying 1 mythium less.',
    }],
  },
];
