import { DeckConfig } from "@worldbreakers/engine";

export const atokEarth: DeckConfig = {
  worldbreakerId: 'khutulun_the_true_daughter',
  cardIds: [
    'khutuluns_kheshig',
    'confident_suitor',
    'the_ten_thousand_ride',
    'call_to_arms',
    'ger_migration',
    'wild_boar_charge',
    'lay_siege',
    'dogtamer',
    'gallant_soldier',
    'kalari_adept',
    'airag_maker',
    'eagle_huntress',
    'skillful_bruiser',
    'amu_river_armorer',
    'champion_of_the_tumen',
    'mongol_quartermaster',
    'poised_duelist',
    'forbidding_guru',
    'sparring_braggart',
    'astute_tactician',
    'tengris_cavalry',
    'the_amu_river_encampment',
    'gratuitous_gift',
    'raid_the_mines',
    'weary_veteran',
    'irate_vandal',
    'lowly_bard',
    'earth_apprentice',
    'swift_messenger',
    'the_humble_underpass'
  ],
}

export const atokStars: DeckConfig = {
  worldbreakerId: 'marco_polo_robed_in_silk',
  cardIds: [
    'silkworm_terrarium',
    'polos_portraitist',
    'exploitative_extraction',
    'proof_of_the_grotto',
    'inspirational_vision',
    'straight_to_the_source',
    'pacify',
    'frantic_getaway',
    'throes_of_fancy',
    'heedless_investor',
    'mothkeeper',
    'sly_sentinel',
    'solemn_guardian',
    'generous_dealer',
    'auspicious_smuggler',
    'suave_sycophant',
    'the_blind_sculptor',
    'illicit_bazaar',
    'mesmerizing_maze',
    'covert_exchange',
    'weaving_workshop',
    'the_uncanny_valley',
    'surprising_development',
    'caravan_guard',
    'lowly_bard',
    'stars_apprentice',
    'the_humble_underpass',
    'the_submerged_brilliance',
    'the_den_of_sabers',
    'the_pit_of_despair',
  ]
}

export const atokVoid: DeckConfig = {
  worldbreakerId: 'ruknuddin_khurshah_leader_of_the_order',
  cardIds: [
    'the_right_hand',
    'alamut_castle',
    'hide_in_plain_sight',
    'amazing_arithmetic',
    // 'stupefy',
    'serpent_strike',
    'vicious_stab',
    // 'consumed_by_the_dust',
    'pernicious_powder',
    // 'novice_cutpurse',
    // 'cunning_reclaimer',
    'resourceful_aide',
    'serendipitous_witness',
    // 'silent_assassin',
    'baleful_viper',
    'alamut_saboteur',
    'alamut_emissary',
    'callous_closer',
    // 'swirling_skirmisher',
    // 'the_ancient_butcher',
    'forlorn_flats',
    'raiders_hideaway',
    'gratuitous_gift',
    'raid_the_mines',
    'mythium_fund',
    'weary_veteran',
    'yam_operator',
    'irate_vandal',
    'swift_messenger',
    'void_apprentice',
  ]
}

export const atokMoon: DeckConfig = {
  worldbreakerId: 'the_muhandasat_council_of_engineers',
  cardIds: [
    // 'ambitious_construction',
    // 'muhandasat_pilot',
    // 'solomons_throne',
    // 'naming_ceremony',
    // 'unveiling_the_council',
    // 'mythium_ingot',
    'bolt_trap',
    // 'surge',
    // 'electrifying_revelation',
    'blood_moon',
    // 'peaceful_engineer',
    // 'fledgling_defender',
    // 'natty_matron',
    // 'steelclad_captain',
    'alert_warden',
    // 'fanciful_astronomer',
    // 'muhandasat_savior',
    // 'nocturnal_reaper',
    // 'patient_mentor',
    // 'the_paragon',
    // 'luminous_lagoon',
    // 'volatile_furnace',
    'surprising_development',
    'mythium_fund',
    // 'desperate_miners',
    'moon_apprentice',
    'the_submerged_brilliance',
    'the_den_of_sabers',
    'the_pit_of_despair',
    'the_indigo_grotto',
  ]
}