import { DeckConfig } from "@worldbreakers/engine";

export const atokEarth: DeckConfig = {
  worldbreakerId: 'khutulun_the_true_daughter',
  cardIds: [
    'khutuluns_kheshig',
    'confident_suitor',
    'the_ten_thousand_ride',
    'call_to_arms',
    'ger_migration',
    'wild_boar_charge',
    'lay_siege',
    'dogtamer',
    'gallant_soldier',
    'kalari_adept',
    'airag_maker',
    'eagle_huntress',
    'skillful_bruiser',
    'amu_river_armorer',
    'champion_of_the_tumen',
    'mongol_quartermaster',
    'poised_duelist',
    'forbidding_guru',
    'sparring_braggart',
    'astute_tactician',
    'tengris_cavalry',
    'the_amu_river_encampment',
    'gratuitous_gift',
    'raid_the_mines',
    'weary_veteran',
    'irate_vandal',
    'lowly_bard',
    'earth_apprentice',
    'swift_messenger',
    'the_humble_underpass'
  ],
}

export const atokStars: DeckConfig = {
  worldbreakerId: 'marco_polo_robed_in_silk',
  cardIds: [
    'silkworm_terrarium',
    'polos_portraitist',
    // 'exploitative_extraction',
    'proof_of_the_grotto',
    'inspirational_vision',
    'straight_to_the_source',
    'pacify',
    'frantic_getaway',
    // 'throes_of_fancy',
    'heedless_investor',
    // 'mothkeeper',
    // 'sly_sentinel',
    // 'solemn_guardian',
    'generous_dealer',
    'auspicious_smuggler',
    // 'suave_sycophant',
    // 'the_blind_sculptor',
    // 'illicit_bazaar',
    // 'mesmerizing_maze',
    'covert_exchange',
    // 'weaving_workshop',
    'the_uncanny_valley',
    'surprising_development',
    'caravan_guard',
    'lowly_bard',
    'stars_apprentice',
    'the_humble_underpass',
    'the_submerged_brilliance',
    'the_den_of_sabers',
    'the_pit_of_despair',
  ]
}